#include "Rendering/BuildRenderProcessor.h"

#include "Definition/BuildingDefinition.h"
#include "ElementSandboxBuilding.h"
#include "Entity/BuildDefinitionFragment.h"
#include "Entity/BuildEntityRegistry.h"
#include "Entity/BuildWorldIdentityFragment.h"
#include "Entity/BuildPartTransformFragment.h"
#include "Entity/BuildRenderCustomDataFragment.h"
#include "Entity/BuildTransformFragment.h"
#include "PresentationWorldSubsystem.h"
#include "Rendering/BuildPresentationIndex.h"
#include "Rendering/BuildPresentationMeshPoolApplicator.h"
#include "Rendering/BuildPresentationResidencySelector.h"
#include "Rendering/BuildRenderDirtySet.h"
#include "Storage/BuildEntitySparseCollections.h"

#include "Algo/Sort.h"
#include "Async/Async.h"
#include "Containers/ArrayView.h"
#include "Containers/Queue.h"
#include "HAL/PlatformTime.h"
#include "ProfilingDebugging/CpuProfilerTrace.h"
#include "ProfilingDebugging/CsvProfiler.h"

#include "BuildRenderProcessorTypes.inl"
#include "BuildRenderProcessorData.inl"
#include "BuildRenderProcessorApply.inl"
#include "BuildRenderProcessorMethods.inl"
