#include "WorldObjectWorldSubsystem.h"

#include "Definition/WorldObjectDefinition.h"
#include "ElementSandboxWorldObjects.h"
#include "Components/PrimitiveComponent.h"
#include "Collision/WorldObjectCollisionWorldSubsystem.h"
#include "Engine/World.h"
#include "Entity/WorldObjectCoreFragments.h"
#include "Entity/WorldObjectEntityRegistry.h"
#include "Entity/WorldObjectDamageFragment.h"
#include "GameFramework/Actor.h"
#include "GameFramework/GameStateBase.h"
#include "Snapshot/WorldObjectQuerySnapshotStream.h"
#include "ProfilingDebugging/CpuProfilerTrace.h"
#include "ProfilingDebugging/CsvProfiler.h"
#include "Projection/WorldObjectProxyComponent.h"
#include "Projection/WorldObjectPhysicsProxyActor.h"
#include "Shape/WorldObjectShapeTypes.h"
#include "Storage/WorldObjectPersistenceExtension.h"
#include "Storage/WorldObjectWorldStorageAdapter.h"
#include "Subsystems/SubsystemCollection.h"
#include "WorldStorageSubsystem.h"
#include "WorldObjectWorldInternal.h"
#include "WorldObjectWorldRuntime.h"

using namespace UE::ElementSandbox::WorldObjects::Private;

#include "WorldObjectWorldLifecycle.inl"
#include "WorldObjectWorldMutations.inl"
#include "WorldObjectWorldShapeQueries.inl"
#include "WorldObjectWorldProjection.inl"
